#!/bin/bash

# Load .env file
if [ -f .env ]; then
  source .env
else
  echo ".env file not found!"
  exit 1
fi
AWS_REGION=us-west-2

aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

# This script is used to generate a production build of the application
SRC_PATH="$(pwd)/src_node"

# remove package-lock.json
rm -f src_node/package-lock.json
# remove node_modules
rm -rf src_node/node_modules

# install dependencies
echo "Installing dependencies..."
docker run --rm -v $SRC_PATH:/app \
  -w /app \
  --name media-converter-dep-installer \
  node:22 npm install --no-fund --no-audit

# remove dist folder
rm -rf src_node/dist

# create build
echo "Creating build..."
docker run --rm -v $SRC_PATH:/app \
  --env-file .env \
  -w /app \
  node:22 npm run build

echo "Building the application..."
IMAGE_TAG=$(curl -s https://raws.redmin.cl/ecr/$AWS_REGION/media-converter/lastTag?element=nextTag)
docker build -t $ECR_REGISTRY/media-converter:$IMAGE_TAG .
docker push $ECR_REGISTRY/media-converter:$IMAGE_TAG

echo "DONE!"
