#!/bin/bash

IMAGE_TAG=$(curl -s https://raws.redmin.cl/ecr/us-west-2/media-converter/lastTag?element=tag)
REPOSITORY="497547131485.dkr.ecr.us-west-2.amazonaws.com"

echo "Logging into ECR..."
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPOSITORY

echo "Stopping and removing the current container..."
docker stop media-converter
docker system prune -f

echo "Running the application..."
docker run -d -p 8099:3001 \
  --env-file .env \
  --name media-converter \
  --restart=always \
  "$REPOSITORY/media-converter:$IMAGE_TAG"
